routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from routes import bcrypt
import src.helpers.fo as fo
from src.helpers.cmd import cmd
from logger import logger


auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = bcrypt.generate_password_hash(request.form['password']).decode('utf-8')
        path = f'data/users/{username}'
        if not fo.f_exist(path):
            # prepare fs
            logger.info(cmd('pwd'))
            cmd(f'cp -r ./data/users/_default ./{path}')
            data = fo.yml2dict(f'{path}/_data.yml')
            data['name'] = username
            data['password'] = password
            fo.dict2yml(data, f'{path}/_data.yml')
            # proceed
            session['user'] = username
            flash('Account created!', 'success')
            return redirect(url_for('index.index'))
        flash('Username already exists!', 'danger')
    return render_template('auth/register.html', page='register')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if username != '_default':
            path = f'./data/users/{username}'
            if fo.d_exist(path):
                saved_password = fo.yml2dict(f'{path}/_data.yml')['password']
                if bcrypt.check_password_hash(saved_password, password):
                    session['user'] = username
                    flash('Login successful!', 'success')
                    return redirect(url_for('index.index'))
        flash('Login failed. Check username and password.', 'danger')
    return render_template('auth/login.html', page='login')

@auth_bp.route('/logout')
def logout():
    session.pop('user', None)
    flash('Logged out!', 'info')
    return redirect(url_for('auth.login'))

routes/index.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, g, jsonify
from functools import wraps
from src.user import User
from src.topics import Topics
from src.topic import Topic
from src.helpers import pdo
from logger import logger
import json


index_bp = Blueprint('index', __name__)
topics = Topics()

# === helpers ===================================
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:
            return redirect(url_for('auth.login'))
        return f(*args, **kwargs)
    return decorated_function

def get_current_user():
    if 'user_obj' not in g:
        g.user_obj = User(session['user'], topics.topiclist) # передавать сюда
    return g.user_obj

# === main menu ===================================
@index_bp.route('/img/favicon.ico')
def favicon():
    return send_from_directory('static', 'img/favicon.ico', mimetype='image/vnd.microsoft.icon')
@index_bp.route('/')
@login_required
def index():
    topics.validate_questions() # validata db_questions
    topics.validate_progress() # validate db_progress
    topics.upd_topicdata() # validate db_stats
    user = get_current_user()
    stats = user.df_stats.to_dict(orient='records')
    return render_template('index.html', page='index', topiclist=topics.topiclist,
                           topicdata=topics.topicdata, stats=stats)

# === topic theory (RAW) ===================================
@index_bp.route('/topic/<int:tid>/theory', methods=['GET'])
@login_required
def topic_theory(tid):
    if tid not in topics.topiclist:
        return "Invalid topic ID", 400
    topic = Topic(tid, topics.topiclist[tid])
    theory_content = topic.theory.strip() if topic.theory else "No theory available."
    return theory_content, 200, {'Content-Type': 'text/plain; charset=utf-8'}

# === topic ===================================
@index_bp.route('/topic/<int:tid>', methods=['GET'])
@login_required
def topic(tid):
    if tid not in topics.topiclist:
        return f'Invalid topic - id:{tid}', 400
    user = get_current_user()
    # Если tid == 0, выбираем реальный топик
    ist0 = 1 if tid == 0 else 0
    chosed_tid = topics.choose_tid(user.df_stats) if tid == 0 else tid
    if chosed_tid not in topics.topiclist:
        return f'Invalid topic - id:{chosed_tid}', 400
    topic = Topic(chosed_tid, topics.topiclist[chosed_tid])
    question = topic.choose_question(user.df_progress)
    # Проверяем, существует ли вопрос
    if not topic.get_question(chosed_tid, question['qkind'], question['qid']):
        return f'Invalid question {chosed_tid}/{question["qkind"]}: {question["qid"]}', 400
    routes = {'choice': 'index.q_choice', 'input': 'index.q_input', 'fill': 'index.q_fill'}
    return redirect(url_for(routes.get(question['qkind'], 'index.unknown_question'),
                            tid=chosed_tid, qid=question['qid'], ist0=ist0))

# === q_helpers ===================================
def init_q_rout(tid, qkind, qid):
    user = get_current_user()
    topic = Topic(tid, topics.topiclist[tid])
    tdata = topics.get_topicdata4topic(tid)
    stat = user.get_stat4topic(tid)
    progress = user.get_progress4question(tid, qkind, qid)
    question = topic.get_question(tid, qkind, qid)
    return user, topic, tdata, stat, progress, question

# === q_choice ===================================
@index_bp.route('/topic/<int:tid>/q_choice/<int:qid>', methods=['GET', 'POST'])
@login_required
def q_choice(tid, qid):
    ist0 = request.args.get('ist0')
    qkind = 'choice'
    user, topic, tdata, stat, progress, question = init_q_rout(tid, qkind, qid)
    if request.method == 'POST':
        answer = sorted(x.strip() for x in request.form.getlist('answer'))
        is_correct = answer == question['correct']
        user.upd_df_progress(tid, qkind, qid, is_correct)
        user.upd_df_stats()
        _, _, tdata, stat, progress, question = init_q_rout(tid, qkind, qid)
        return jsonify({
            'tdata': tdata,
            'stat': stat,
            'progress': progress,
            'question': question,
            'answer': answer,
            'is_correct': is_correct,
        })
    return render_template('q_choice.html', page='q_choice', tdata=tdata,
                           question=question, progress=progress, stat=stat, ist0=ist0)

# === q_input ===================================
@index_bp.route('/topic/<int:tid>/q_input/<int:qid>', methods=['GET', 'POST'])
@login_required
def q_input(tid, qid):
    ist0 = request.args.get('ist0')
    qkind = 'input'
    user, topic, tdata, stat, progress, question = init_q_rout(tid, qkind, qid)
    if request.method == 'POST':
        answer = request.form.get('answer')
        is_correct = answer.strip().lower() == question['correct'].strip().lower()
        user.upd_df_progress(tid, qkind, qid, is_correct)
        user.upd_df_stats()
        _, _, tdata, stat, progress, question = init_q_rout(tid, qkind, qid)
        return jsonify({
            'tdata': tdata,
            'stat': stat,
            'progress': progress,
            'question': question,
            'answer': answer,
            'is_correct': is_correct,
        })
    return render_template('q_input.html', page='q_input', tdata=tdata,
                           question=question, progress=progress, stat=stat, ist0=ist0)

# === q_fill ===================================
@index_bp.route('/topic/<int:tid>/q_fill/<int:qid>', methods=['GET', 'POST'])
@login_required
def q_fill(tid, qid):
    ist0 = request.args.get('ist0')
    qkind = 'fill'
    user, topic, tdata, stat, progress, question = init_q_rout(tid, qkind, qid)
    if request.method == 'POST':
        answer = request.form.get('answer')
        user_answers = [ans.strip().lower() for ans in json.loads(answer)]
        correct_answers = [item[1].strip().lower() for item in question["correct"]]
        is_correct = user_answers == correct_answers
        user.upd_df_progress(tid, qkind, qid, is_correct)
        user.upd_df_stats()
        _, _, tdata, stat, progress, question = init_q_rout(tid, qkind, qid)
        return jsonify({
            'tdata': tdata,
            'stat': stat,
            'progress': progress,
            'question': question,
            'answer': answer,
            'is_correct': is_correct,
        })
    return render_template('q_fill.html', page='q_fill', tdata=tdata,
                           question=question, progress=progress, stat=stat, ist0=ist0)

# === suspicious ===================================
@index_bp.route('/suspicious', methods=['POST'])
@login_required
def mark_suspicious():
    data = request.json
    return jsonify({'success': topics.mark_suspicious(data)})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Default Title{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/helpers.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
</head>
<body class='dflex p0 m0'>
  <div class='wrap dflex col p10'>
    {% include 'components/messages.html' %}
    <header class="dflex row jc-between ai-center">
      <div class="title dflex p5">{% block header %}Header{% endblock %}</div>
      {% if page not in ['login', 'register'] %}
        <div class="logout">
          <a href="{{ url_for('auth.logout') }}" class="logout-btn ai-end pb5">Logout</a>
        </div>
      {% endif %}
    </header>
    <main class='container p5'>
      {% block content %}{% endblock %}
    </main>
  </div>
  <script type='module' src="{{ url_for('static', filename='js/'+page+'.js') }}"></script>
  {% if page in ['q_choice', 'q_input', 'q_fill'] %}
    <script type="module" src="{{ url_for('static', filename='js/suspicious.js') }}"></script>
  {% endif %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Main Menu{% endblock %}
{% block header %}
  <span>MainMenu</span>
{% endblock %}
{% block content %}
<section class="topics">
  <table id="topics-table">
    <thead>
      <tr>
        <th class="ph5">Topic</th>
        <th class="ph5">Stats and Progress</th>
      </tr>
    </thead>
    <tbody>
      {% set vim_keys = ['s', 'd', 'f', 'w', 'e', 'r', '2', '3', '4', 'c'] %}
      {% for tid, tname in topiclist.items() %}
        {% set vim_shortcut = vim_keys[loop.index - 1] if loop.index0 < vim_keys|length else '' %}
        {% set stat = stats | selectattr("tid", "equalto", tid) | first | default({}) %}
        {% set tdata = topicdata | selectattr("tid", "equalto", tid) | first | default({}) %}
        <tr data-topic-id="{{ tid }}" class="topic-row">
          <td class="topic_name">
            <div class='dflex'>
              {% if vim_shortcut %}
                <span class="shortcut-key m5 r">{{ vim_shortcut if vim_shortcut else '' }}:</span>
              {% endif %}
              <a href="{{ url_for('index.topic', tid=tid|int) }}" class="topic-link dflex ai-center">{{ tname }}</a>
            </div>
          </td>
          <td class="topic_stats">
            <div class="stats dflex row ai-center jc-between">
              <div class="stats-left dflex row">
                {% for grade in ['F', 'D', 'C', 'B', 'A', 'N'] %}
                  <span id="stat-{{ grade }}" class="stat {{ 'zero' if stat.get(grade, 0) == 0 else grade }} p5">
                    {{ grade }}:{{ stat.get(grade, 0) }}
                  </span>
                {% endfor %}
              </div>
              <div class="stats-right dflex row">
                <span id="total" class="total p5">{{ tdata.get('in_progress', 0) }}/{{ tdata.get('total', 1) }}</span>
                <span id="suspicious" class="suspicious p5 {{ 'zero' if tdata.get('suspicious', 0) == 0 else 'found' }}">
                  ?:{{ tdata.get('suspicious', 0) }}
                </span>
              </div>
            </div>
            <div class="progress-bar dflex w100">
              {% set total = stat.get('total', 1) %}
              {% for grade in ['F', 'D', 'C', 'B', 'A', 'N'] %}
                {% set width = (stat.get(grade, 0) / total * 100) if total else 0 %}
                <div class="sub-progress {{ grade }} {{ 'dnone' if width == 0 }}" style="width: {{ width }}%;"></div>
              {% endfor %}
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
{% endblock %}

templates/q_choice.html
{% extends 'base.html' %}
{% block title %}Q-choice{% endblock %}
{% block header %}
  <a id='main-menu-link' href='{{ url_for('index.index') }}'>MainMenu</a>
  <span>/</span>
  <a id='theory-link' href='{{ url_for('index.topic_theory', tid=tdata.tid) }}'>{{ tdata.tid }}.{{ tdata.tname }}</a>
  <span>/Q-choice</span>
{% endblock %}
{% block content %}
<div id='ist0' class='dnone' data-ist0="{{ ist0 }}"></div>
<section id='q_choice' class='q_choice'>
  {% include 'components/q_header.html' %}
  {% include 'components/q_suspicious_msgs.html' %}
  {% include 'components/q_hints.html' %}
  {% include 'components/q_question.html' %}
  {% include 'components/q_extra.html' %}
  {{ tdata }}
  <form id='question-form' class='question-form dflex col pt10 pb5'
    autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'
    action='{{ url_for("index.q_choice", tid=tdata.tid, qid=question.id) }}' method='post'>
    <div class='options'>
      {% set vim_keys = ['s', 'd', 'f', 'w', 'e', 'r', '2', '3', '4', 'c'] %}
      {% for option in question.options %}
        {% set vim_shortcut = vim_keys[loop.index - 1] if loop.index - 1 < vim_keys|length else '' %}
        <input class='option-input' type='checkbox' id='option{{ loop.index }}' name='answer' value='{{ option }}'>
        <label for='option{{ loop.index }}' class='option-label m0 m5 dflex row ai-center jc-start'>
          {% if vim_shortcut %}
            <span class='shortcut-key m5 r'>{{ vim_shortcut }}:</span>
          {% endif %}
          <span class='option-text fx1 m5 p5 bg-w brd-w hov'>{{ option }}</span>
        </label>
      {% endfor %}
    </div>
    <div class='form-footer dflex row jc-between ai-center mt5'>
      <div class='submit-section dflex row jc-start ai-center mt10'>
        <button id='form-btn-submit' class='form-btn-submit btn btn-g m5 pv5 ph10' type='submit'>Submit</button>
        <button id='form-btn-next-question' class='form-btn-next-question dnone btn m5 pv5 ph10'>Next Question</button>
        <p id='msg-result' class='msg-result dnone m0 p0 pl10'></p>
        <p id="msg-empty" class="msg-empty dnone r m0 p0 pl10">Please select at least one option.</p>
      </div>
      {% include 'components/q_suspicious_form.html' %}
    </div>
  </form>
</section>
{% endblock %}

templates/q_choose.html
{% extends 'base.html' %}
{% block title %}Q-Choose{% endblock %}
{% block header %}
  <a id='main-menu-link' href='{{ url_for('index.index') }}'>MainMenu</a>
  <span>/</span>
  <a id='theory-link' href='{{ url_for('index.topic_theory', tid=tdata.tid) }}'>{{ tdata.tid }}.{{ tdata.tname }}</a>
  <span>/Q-Choose</span>
{% endblock %}
{% block content %}
<div id='ist0' class='dnone' data-ist0="{{ ist0 }}"></div>
<section id='q_choose' class='q_choose'>
  {% include 'components/q_header.html' %}
  {% include 'components/q_suspicious_msgs.html' %}
  {% include 'components/q_hints.html' %}
  {% include 'components/q_question.html' %}
  {% include 'components/q_extra.html' %}
  {{ tdata }}
  <form id='question-form' class='question-form dflex col pt10 pb5'
    autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'
    action='{{ url_for("index.q_choose", tid=tdata.tid, qid=question.id) }}' method='post'>
    <div class='options'>
      {% set vim_keys = ['s', 'd', 'f', 'w', 'e', 'r', '2', '3', '4', 'c'] %}
      {% for option in question.options %}
        {% set vim_shortcut = vim_keys[loop.index - 1] if loop.index - 1 < vim_keys|length else '' %}
        <input class='option-input' type='checkbox' id='option{{ loop.index }}' name='answer' value='{{ option }}'>
        <label for='option{{ loop.index }}' class='option-label m0 m5 dflex row ai-center jc-start'>
          {% if vim_shortcut %}
            <span class='shortcut-key m5 r'>{{ vim_shortcut }}:</span>
          {% endif %}
          <span class='option-text fx1 m5 p5 bg-w brd-w hov'>{{ option }}</span>
        </label>
      {% endfor %}
    </div>
    <div class='form-footer dflex row jc-between ai-center mt5'>
      <div class='submit-section dflex row jc-start ai-center mt10'>
        <button id='form-btn-submit' class='form-btn-submit btn btn-g m5 pv5 ph10' type='submit'>Submit</button>
        <button id='form-btn-next-question' class='form-btn-next-question dnone btn m5 pv5 ph10'>Next Question</button>
        <p id='msg-result' class='msg-result dnone m0 p0 pl10'></p>
        <p id="msg-empty" class="msg-empty dnone r m0 p0 pl10">Please select at least one option.</p>
      </div>
      {% include 'components/q_suspicious_form.html' %}
    </div>
  </form>
</section>
{% endblock %}

templates/q_fill.html
{% extends 'base.html' %}
{% block title %}Q-Fill{% endblock %}
{% block header %}
  <a id='main-menu-link' href='{{ url_for('index.index') }}'>MainMenu</a>
  <span>/</span>
  <a id='theory-link' href='{{ url_for('index.topic_theory', tid=tdata.tid) }}'>{{ tdata.tid }}.{{ tdata.tname }}</a>
  <span>/Q-Fill</span>
{% endblock %}
{% block content %}
<div id='ist0' class='dnone' data-ist0="{{ ist0 }}"></div>
<section class='q_fill'>
  {% include 'components/q_header.html' %}
  {% include 'components/q_suspicious_msgs.html' %}
  {% include 'components/q_hints.html' %}
  <p class='question-block dflex m0'>
    <strong class='b bg-b mr5'>Q:</strong>
    <span>Please fill in the gaps.<span>
  </p>
  <pre id='question-text' class='question-text p10 m0'>{{ question.question | safe }}</pre>
  <form id='question-form' class='question-form dflex col jc-between pt5'
    autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'
    action='{{ url_for("index.q_fill", tid=tdata.tid, qid=question.id) }}' method='post'>
    <input id='form-input' class='form-input m0 p0'
        autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' type='text' autofocus>
    <input id="hidden-answer" name="answer" type="hidden">
    <div class='form-footer dflex row jc-between ai-center'>
      <div class='form-btns-section dflex row jc-start ai-center'>
        <button id='form-btn-back' type='button' class='form-btn-back dnone btn btn-y mr5 pv5 ph10'>Back</button>
        <button id='form-btn-next' type='button' class='form-btn-next dnone btn btn-b mr5 pv5 ph10'>Next</button>
        <button id='form-btn-submit' type='submit' class='form-btn-submit dnone btn btn-g pv5 ph10'>Submit</button>
        <button id='form-btn-next-question' class='form-btn-next-question dnone btn pv5 ph10'>Next Question</button>
        <p id='msg-result' class='msg-result dnone m0 p0 pl10'></p>
        <p id='msg-empty' class='dnone msg-empty r m0 p0 pl10'>The input field should not be empty.</p>
      </div>
      {% include 'components/q_suspicious_form.html' %}
      {{ question.extra }}
    </div>
  </form>
</section>
{% endblock %}

templates/q_input.html
{% extends 'base.html' %}
{% block title %}Q-Input{% endblock %}
{% block header %}
  <a id='main-menu-link' href='{{ url_for('index.index') }}'>MainMenu</a>
  <span>/</span>
  <a id='theory-link' href='{{ url_for('index.topic_theory', tid=tdata.tid) }}'>{{ tdata.tid }}.{{ tdata.tname }}</a>
  <span>/Q-Input</span>
{% endblock %}
{% block content %}
<div id='ist0' class='dnone' data-ist0="{{ ist0 }}"></div>
<section class='q_input'>
  {% include 'components/q_header.html' %}
  {% include 'components/q_suspicious_msgs.html' %}
  {% include 'components/q_question.html' %}
  {% include 'components/q_hints.html' %}
  {% include 'components/q_extra.html' %}
  <form id='question-form' class='question-form dflex col jc-between pt10 pb5'
        autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'
        action='{{ url_for("index.q_input", tid=tdata.tid, qid=question.id) }}' method='post'>
    <input id='form-input' class='form-input' type='text' name='answer' placeholder='Your answer...' autofocus>
    <div class='form-footer dflex row jc-between ai-center mt5'>
      <div class='submit-section dflex row jc-start ai-center'>
        <button id='form-btn-submit' type='submit' class='submit btn btn-g pv5 ph10'>Submit</button>
        <button id='form-btn-next-question' class='next-question dnone btn pv5 ph10'>Next Question</button>
        <p id='msg-result' class='msg-result dnone m0 p0 pl10'></p>
        <p id='msg-empty' class='msg-empty dnone r m0 p0 pl10'>Please input an answer.</p>
      </div>
      {% include 'components/q_suspicious_form.html' %}
    </div>
  </form>
</section>
{% endblock %}

templates/q_select.html
{% extends 'layouts/base.html' %}
{% block title %}Q-Select{% endblock %}
{% block header %}Q-Select{% endblock %}
{% block content %}
<div class="container">
  {% include 'layouts/messages.html' %}
  <section class="q_select">
    <h3>Q-Select</h3>

    {{ q }}

  </section>
</div>
{% endblock %}

templates/q_single.html
{% extends 'layouts/base.html' %}
{% block title %}Q-Single{% endblock %}
{% block header %}Q-Single{% endblock %}
{% block content %}
<div class="container">
  {% include 'layouts/messages.html' %}
  <section class="q_single">
    <h3>Q-Single</h3>
     
    {{ q }}

    <!-- <h1>{{ q.category_eng }}</h1> -->
    <!-- <h3>({{ q.category_ru }})</h3> -->
    <!-- <form action="/mode/pronouns" method="post"> -->
    <!--     <p>{{ q_text | safe }}</p> -->
    <!--     <button type="submit">Send</button> -->
    <!-- </form> -->
    <!-- {% if result is not none %} -->
    <!--     <p>Your answer: {{ answer }}</p> -->
    <!--     <p>{% if result %}✔ Correct!{% else %}❌ Incorrect! The correct answer is: {{ q.pronoun_clean }}{% endif %}</p> -->

  </section>
</div>
{% endblock %}